layout_spectrum: 0.6957058069499965
typography_spectrum: 0.5170022057539018
color:
  brandStrength: 0.2019941986284892
  lightness: 0.3008949638542599
  saturation: 0.5966457525412044
  rhythmicContrast: 0.23336614290556623
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Coagulatio
content: []
title: Coagulatio
description: ultima materia
github: true
url: 'https://coagulatio.puro.cc'
author:
  name: Rodrigo Franco
  email: rodrigofesteves@gmail.com
  url: 'http://coagulatio.puro.cc'
